### PR TITLE
Wassa2023 data and training/eval notebooks

### PR DESCRIPTION
**Pull request by maxaalexeeva**

### CODE REVIEW

**Comment by maxaalexeeva** [comment]
@MihaiSurdeanu, there are some columns in some tsvs that are not strictly necessary, e.g., tokenized sentence. Also, there might be a column or two that have the same information but are named slightly different (eg tokenized_sentence vs tok_sents)---is it worth it going through them to check for consistency? Arguments against renaming/deleting columns are a. it takes time (which is fine) and b. sometimes editing files locally messes up tsvs.

**Comment by MihaiSurdeanu** [comment]
I think we should keep the data as close as possible to the paper. So, I recommend to keep it as is.
Merge?

**Comment by maxaalexeeva** [comment]
Yes, I think providing too much info is better than not enough. Should be ok to merge then. Thanks!

**Comment by MihaiSurdeanu** [comment]
Merged! Thanks!

**Pull request merged**
